ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJm/RzeIkS0Hor9zXTGCwTbtthGqkTdCb4e8eF/MAk2MT5TpIaQw3W0eNFyEzKixoKdU87vST77rpqn6sryjjUMCAwEAAQ==
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl: 
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost