ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: CtilV3SOig6Lv3EBAYtzXU=kn2Jk=OK?lDBKpGIp/5VThN?8L3P6-vo0gscHYclN
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl: 
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost