ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'
  auth:
    jwtSecret: z3EKtLI70MqTmat7tzhzA4LO1bQBe000gXdbS6tqE65HFtEmPzcVfP4dQU2Iwpf5OgmTPKzTmyTV3DQK00IEvmFMFsuiUQFB0WcbKrpjtkXDxnV4UjxYJuOClQzq9dS0uFsVDxfpAhfD9VmbmzDLcU3LYb3cTOQqUSgMCC3SELJo9nXHc8FXHw7jRqssSY04t74RUmIKdyp1ZQ68hocbGWEBUuRHnTBuERCUClNaGrFKhFxZh4K5M8Oy3CcdEvv6HxMz5ZL805AhLr28knehwCc7k2LLnTrqPZV8VWRBQmhgKoPXdIOYvh9h8TyzRvUx9dLGd6Nog1mZvq6MG3Ci8c74UlyGph92pPR8SDaZNdHdBUxWzI8kWKO3MTGaWi5YHcffKMhG5W2kT4AUFvAJnijRpZEBHS5NfrnMonvYseXTO381vtJwjdbqTNj3b5mxfJg17K8jHNxAgGFSC066ogSjzUx1fBVYYVN4kTiNaaybi4y6Zg4KsGARW3v6Mbgf
    jwtExpirationMs: 14400000

eureka:
  client:
    serviceUrl: 
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost